name: publish

on: { push: { branches: [main] } }

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup PNPM
        uses: pnpm/action-setup@v3
        with: { version: 'latest' }

      - name: setup Node
        uses: actions/setup-node@v4
        with: { node-version: 'latest' }

      - name: install
        run: pnpm install

      - name: check
        run: |
          pnpm tsc --noEmit;
          pnpm prettier --ignore-path .gitignore --log-level warn --check .;
          pnpm eslint --report-unused-disable-directives .;

      - name: publish
        run: pnpm publish --access=restricted
        env:
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
