name: publish

on: { push: { branches: [main] } }

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup PNPM
        uses: pnpm/action-setup@v3
        with: { version: 'latest' }

      - name: setup Node
        uses: actions/setup-node@v4
        with: { node-version: 'latest' }

      - name: setup / build
        run: pnpm run setup

      - name: check
        run: pnpm run lint

      - name: publish
        run: pnpm publish --access=public
